[parity]
chain = "./genesis.json" 
base_path = "./" 

[network]
port = 30303
reserved_peers=  "./nodes" 
allow_ips = "all"

[rpc]
port = 8545
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces" ,"rpc", "parity_accounts"]

[websockets]
disable = false
port = 8546

[account]
password = ["./password"] 

[mining]
engine_signer = "0xae203a3d00e7c0ea613abfc9f284eaee7da74031"  # validator에 등록한 계정중 하나 넣기
gas_floor_target = "40000000"

[misc]
logging = "own_tx=trace"
log_file = "./log.log"
color = true